services:
  db:
    # Используем официальную сборку PostGIS для поддержки расширения postgis
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: gov_services
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Server.Api/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=gov_services;Username=postgres;Password=postgres
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5001:80"

  client:
    build:
      context: .
      dockerfile: Client.Wasm/Dockerfile
    depends_on:
      - server
    ports:
      - "5002:80"

  vector-db:
    image: qdrant/qdrant
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  agent:
    build:
      context: .
      dockerfile: agent/Dockerfile
    depends_on:
      - db
      - vector-db
    volumes:
      - ./data/docs:/app/data/docs
      - ./data/forms:/app/data/forms
      - ./data/maps:/app/data/maps
    environment:
      - MODEL_PATH=/app/models
      - QDRANT_URL=http://vector-db:6333
      - POSTGRES_CONNECTION=Host=db;Port=5432;Database=gov_services;Username=postgres;Password=postgres
    ports:
      - "8000:8000"

volumes:
  pgdata:
  qdrant_data:
