services:
  db:
    # Используем официальную сборку PostGIS для поддержки расширения postgis
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_DB: gov_services
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Server.Api/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=gov_services;Username=postgres;Password=postgres;Include Error Detail=true
      ASPNETCORE_URLS: http://+:80
    ports:
      - "5001:80"

  client:
    build:
      context: .
      dockerfile: Client.Wasm/Dockerfile
    depends_on:
      - server
    environment:
      - API_BASE_URL=http://server
    ports:
      - "5002:80"

  # vector-db and python agent removed; document classification handled by ASP.NET API

volumes:
  pgdata:
