FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Client.Wasm/Client.Wasm.csproj", "Client.Wasm/"]
RUN dotnet restore "Client.Wasm/Client.Wasm.csproj"
COPY . .
WORKDIR "/src/Client.Wasm"
RUN dotnet publish -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/publish/wwwroot .
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
